### ISSUE TITLE
Add support for pushing/uploading translations

### ISSUE THREAD

**Issue by tobiaslieandersen** [StyleShare/poeditor-cli#2]
The `pull` function works great, but I'm missing a `push` feature that enables uploading of translations to POEditor for both Android strings and Apple strings

**Comment by devxoul** [comment]
@tobiaslieandersen Thanks for your interests. Actually I'm not much experienced in working with translation files, so I can't understand the needs of `push` operation. Could you provide me some details? It'll be great if you can share me your workflow. For example, I'm working with translation files as following (that doesn't need uploading stuff):

1. Add new terms to POEditor on https://poeditor.com
1. Develop with new term keys (not yet translated)
1. Commit
1. Ask translators for translation
1. Pull translated strings from POEditor to project
1. Commit

**Comment by tobiaslieandersen** [comment]
@devxoul Thanks for the quick reply! 

This is my first experience with POEditor, so I'm sort of creating a workflow as I go. My plan was to be able to do everything through the IDE and terminal, and create the terms as we develop. And then with every commit or so, push the changes. 

But your workflow makes a lot of sense as it ensures better sync between iOS and Android, and a better interface of editing terms then through `.strings` files. I'm also not sure how deleted terms would be handled when pushing to poeditor. I guess I just thought of poeditor.com as a strings repository to sync strings, and not the strings editor it actually is.

Thanks for an awsome tool! 👍
